{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "autocache.fullname" . }}
  labels:
    {{- include "autocache.labels" . | nindent 4 }}
rules:
# Manage AutoCache CRs
- apiGroups:
  - cache.autocache.io
  resources:
  - autocaches
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cache.autocache.io
  resources:
  - autocaches/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - cache.autocache.io
  resources:
  - autocaches/finalizers
  verbs:
  - update
# Manage StatefulSets
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# Manage Services and ConfigMaps
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# Watch Pods
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
# Read Secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
# Events for debugging
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
{{- end }}
